name: Update Blog Posts on Profile

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser beautifulsoup4

    - name: Fetch and process RSS feed
      run: |
        python <<EOF
        import feedparser
        from bs4 import BeautifulSoup
        import os

        # Parse the RSS feed
        feed = feedparser.parse("https://nin-blog.vercel.app/index.xml")

        # Filter items where guid starts with the post URL
        blog_posts = [entry for entry in feed.entries 
                     if entry.get('guid', '').startswith('https://ninblog.ycstation.work/post/')]

        # Prepare markdown content
        markdown_content = "## Latest Blog Posts\\n\\n"
        markdown_content += "<table>\\n"
        
        for post in blog_posts[:5]:  # Get latest 5 posts
            # Format the date nicely
            try:
                from datetime import datetime
                date_obj = datetime.strptime(post.published[:10], '%Y-%m-%d')
                # Format with emoji and better styling
                pub_date = f"📅 {date_obj.strftime('%a, %d %b %Y')}"
            except:
                pub_date = f"📅 {post.published[:10]}"
            
            # Create a simpler, cleaner format with emoji
            markdown_content += f"<tr>\\n"
            markdown_content += f"  <td>📝</td>\\n"
            markdown_content += f"  <td><a href='{post.link}'>{post.title}</a></td>\\n"
            markdown_content += f"  <td><code>{pub_date}</code></td>\\n"
            markdown_content += f"</tr>\\n"
        
        markdown_content += "</table>\\n"
        
        # Add update timestamp
        from datetime import datetime
        current_time = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
        markdown_content += f"\\n<p align='right'><sup><i>Last updated: {current_time}</i></sup></p>\\n"

        # Update README.md
        readme_path = 'README.md'
        
        # Read existing content
        with open(readme_path, 'r') as f:
            content = f.read()
        
        # Find and replace the blog posts section
        start_marker = "<!-- BLOG-POSTS:START -->"
        end_marker = "<!-- BLOG-POSTS:END -->"
        
        start_index = content.find(start_marker) + len(start_marker)
        end_index = content.find(end_marker)
        
        new_content = content[:start_index] + "\\n" + markdown_content + "\\n" + content[end_index:]
        
        # Write back to file
        with open(readme_path, 'w') as f:
            f.write(new_content)
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update latest blog posts" || echo "No changes to commit"
        git push