name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://ninblog.ycstation.work/index.xml
          count: 5
      - name: Filter RSS content
        run: |
          # Example: Only keep lines containing a specific URL pattern
          sed -i '/https:\/\/ninblog.ycstation.work\/post\//!d' README.md
      - name: Commit file changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet --cached || git commit -m "Update README with latest blog posts"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}