name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ninblog.ycstation.work/index.xml"
          max_post_count: 5
          template: "- [**$title**]($url) - $date\n  > $description"
          filter_comments: "https://ninblog.ycstation.work/post/"
          date_format: "yyyy-MM-dd"
          description_max_length: 100
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          accept_header: "text/xml, application/xml, application/rss+xml, application/atom+xml"
          retry_count: 3
          retry_wait_time: 10