name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"          # Set to "True" to show projects
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"         # Set to "True" to show the lines of code chart
          SHOW_DAYS_OF_WEEK: "True"      # Set to "True" to show coding days
          SHOW_SHORT_INFO: "True"        # Set to "True" for additional stats
          SHOW_LANGUAGE_PER_REPO: "True" # Set to "True" to show languages per repo
          SHOW_PROFILE_VIEWS: "True"     # Set to "True" to show profile views
          SHOW_TOTAL_CODE_TIME: "True"   # Set to "True" to show total code time
          SHOW_EDITORS: "True"           # Set to "True" to show editors used
          SHOW_TIMEZONE: "True"          # Set to "True" to show timezone